# Generated by Django 5.0 on 2024-12-10 08:14

import autoslug.fields
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_sales_receipt_is_cash_alter_account_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finish_Product_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 13, 14, 54, 151219)),
        ),
        migrations.CreateModel(
            name='Final_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255, unique=True)),
                ('product_size', models.CharField(max_length=255)),
                ('product_quantity', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(default='Nos', max_length=255)),
                ('weight', models.FloatField(blank=True, default=0, max_length=255, null=True)),
                ('product_status', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pro_img', models.ImageField(null=True, upload_to='uploaded/products/')),
                ('product_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='productname', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.finish_product_category')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Issue_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Issue_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.product')),
                ('store_isuue_note', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.store_issue_note')),
            ],
        ),
        migrations.AddField(
            model_name='store_issue_note',
            name='products',
            field=models.ManyToManyField(through='home.Store_Issue_Product', to='home.product'),
        ),
        migrations.CreateModel(
            name='Store_Purchase_Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Purchase_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.product')),
                ('store_purchase_note', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.store_purchase_note')),
            ],
        ),
        migrations.AddField(
            model_name='store_purchase_note',
            name='products',
            field=models.ManyToManyField(through='home.Store_Purchase_Product', to='home.product'),
        ),
    ]
