# Generated by Django 5.0 on 2024-12-10 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_finish_product_category_project_product_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 10, 18, 10, 25, 671971)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded/products/'),
        ),
    ]
