# Generated by Django 5.0 on 2024-12-12 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_custompermissions_alter_account_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='custompermissions',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_balance_sheet', 'Can view balance sheet')]},
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 12, 19, 14, 285648)),
        ),
    ]
