# Generated by Django 5.0 on 2024-12-12 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_blog_options_alter_custompermissions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 12, 49, 32, 260978)),
        ),
    ]
