# Generated by Django 5.0 on 2024-12-12 09:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_account_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 14, 21, 46, 111950)),
        ),
        migrations.AlterField(
            model_name='final_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.finish_product_category'),
        ),
    ]
