# Generated by Django 5.0 on 2024-12-12 09:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_account_date_alter_final_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 14, 24, 10, 294919)),
        ),
        migrations.AlterField(
            model_name='final_product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.finish_product_category'),
        ),
    ]
