# Generated by Django 5.0 on 2024-12-12 10:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_account_date_alter_final_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 15, 13, 4, 67447)),
        ),
        migrations.AlterField(
            model_name='store_purchase_note',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.project'),
        ),
    ]
