# Generated by Django 5.0 on 2024-12-12 11:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_custompermissions_options_alter_account_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 27, 13, 947839)),
        ),
        migrations.AlterField(
            model_name='store_issue_note',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.project'),
        ),
    ]
