# Generated by Django 5.0 on 2024-12-12 11:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_account_date_alter_store_issue_note_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 12, 16, 29, 12, 391606)),
        ),
        migrations.AlterField(
            model_name='store_purchase_note',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.project'),
        ),
    ]
