# Generated by Django 5.0 on 2024-12-19 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_account_date_alter_store_purchase_note_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store_issue_product',
            old_name='store_isuue_note',
            new_name='store_issue_note',
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 19, 23, 20, 22, 762113)),
        ),
    ]
