# Generated by Django 5.1 on 2024-12-30 07:39

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_rename_store_isuue_note_store_issue_product_store_issue_note_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompermissions',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_balance_sheet', 'Can view balance sheet'), ('view_store', 'Can view store'), ('view_reports', 'Can view reports'), ('view_inventory', 'Can view inventory')]},
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 12, 39, 37, 306801)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=autoslug.fields.AutoSlugField(default=None, null=True, unique=True),
        ),
    ]
