# Generated by Django 5.1 on 2025-01-22 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_custompermissions_options_alter_account_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_construction', models.BooleanField(blank=True, help_text='Note for Under Costruction', null=True)),
                ('uc_note', models.TextField(blank=True, help_text='Note for under construction', null=True)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='End date and time for under construction mode', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 12, 10, 23, 912059)),
        ),
    ]
