# Generated by Django 5.1 on 2025-01-28 07:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_underconstruction_alter_account_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='made_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 23, 37, 529664)),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['debit_account'], name='home_transa_debit_a_0e4eda_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['credit_account'], name='home_transa_credit__33a65f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='home_transa_date_a8ccfc_idx'),
        ),
    ]
