# Generated by Django 5.0 on 2025-01-28 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_transaction_made_by_alter_account_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 28, 12, 54, 59, 583917)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.BooleanField(default=False),
        ),
    ]
