# Generated by Django 5.0 on 2025-01-31 09:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_account_date_alter_product_product_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 14, 15, 39, 748169)),
        ),
        migrations.CreateModel(
            name='Store_Issue_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.project')),
            ],
        ),
        migrations.CreateModel(
            name='Store_Issue_Request_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.product')),
                ('store_issue_request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.store_issue_request')),
            ],
        ),
        migrations.AddField(
            model_name='store_issue_request',
            name='products',
            field=models.ManyToManyField(through='home.Store_Issue_Request_Product', to='home.product'),
        ),
    ]
