# Generated by Django 5.0 on 2025-01-31 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_account_date_store_issue_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_issue_request',
            name='issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 12, 6, 11643)),
        ),
    ]
