# Generated by Django 5.0 on 2025-01-31 14:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_store_issue_request_issue_alter_account_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_issue_note',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.store_issue_request'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 46, 16, 796350)),
        ),
    ]
