# Generated by Django 5.1 on 2025-02-02 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_store_issue_note_request_alter_account_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 10, 12, 24, 834540)),
        ),
    ]
