# Generated by Django 5.1 on 2025-06-15 06:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_account_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store_issue_request',
            name='issued_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_issued', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 11, 24, 43, 562268)),
        ),
        migrations.AlterField(
            model_name='store_issue_note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_issue_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store_issue_note',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_issue_notes', to='home.project'),
        ),
        migrations.AlterField(
            model_name='store_issue_note',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requested_issue_notes', to='home.store_issue_request'),
        ),
        migrations.AlterField(
            model_name='store_issue_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issued_in_notes', to='home.product'),
        ),
        migrations.AlterField(
            model_name='store_issue_product',
            name='store_issue_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='store_products', to='home.store_issue_note'),
        ),
        migrations.AlterField(
            model_name='store_issue_request',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store_issue_request',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_requests', to='home.project'),
        ),
        migrations.AlterUniqueTogether(
            name='store_issue_product',
            unique_together={('store_issue_note', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='store_issue_request_product',
            unique_together={('store_issue_request', 'product')},
        ),
    ]
