# Generated by Django 5.1 on 2025-06-15 08:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_account_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 15, 13, 7, 59, 19613)),
        ),
        migrations.AlterField(
            model_name='store_issue_request_product',
            name='store_issue_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='store_issue_request_products', to='home.store_issue_request'),
        ),
    ]
