# Generated by Django 5.2.5 on 2025-09-10 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_account_address_account_contact_account_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 21, 52, 29, 192930)),
        ),
    ]
