# Generated by Django 5.2.5 on 2025-09-10 18:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_account_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_img',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.AddField(
            model_name='product',
            name='default_store',
            field=models.CharField(choices=[('Store1', 'Store1'), ('Store2', 'Store2'), ('Store3', 'Store3')], default='Store1', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='final_product_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.final_product'),
        ),
        migrations.AddField(
            model_name='product',
            name='labour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stockable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 23, 31, 3, 273592)),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
