# Generated by Django 5.2.5 on 2025-09-10 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_remove_product_pro_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 23, 42, 27, 373555)),
        ),
        migrations.AlterField(
            model_name='product',
            name='default_store',
            field=models.CharField(choices=[('Store1', 'Store1'), ('Store2', 'Store2'), ('Store3', 'Store3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Nos', 'Nos'), ('Kgs', 'Kgs')], default='Nos', max_length=50),
        ),
    ]
